# Chapter 0.5: Intro To Python

## Introduction

The only hard requirement for this course is knowing a bit about the Python programming language.

In this introductory chapter we quickly go over some features of Python. This should be enough for you to understand the code presented in the rest of the chapters.

These slides were made with both people who are comfortable with programming and beginners in mind. Don't worry if you do not understand some programming terms, just ignore them.

## Python

Python is an interpreted dynamically typed programming language. Code blocks are denoted using whitespace.

Here is a simple program in Python:

In [1]:
x = 3

if x % 2 == 0:
  print(f"x={x} is even")
else:
  print(f"x={x} is odd")

x=3 is odd


## Python

If you want to do an `else if` statement you have to do it like this:

In [2]:
x = 5

if x == 0:
  print(f"x={x} is equal to zero")
elif x > 0:
  print(f"x={x} is positive")
else:
  print(f"x={x} is negative")

x=5 is positive


## Python

Here is how to loop:

In [3]:
for _ in range(3):
  print("Hello from for loop!")

i = 0
while i < 3:
  print("Hello from while loop!")
  i += 1

Hello from for loop!
Hello from for loop!
Hello from for loop!
Hello from while loop!
Hello from while loop!
Hello from while loop!


## Python

Variable's type is inferred during assignment.

In [4]:
x = 5
print(f"x type is {type(x)}")
y = 5.
print(f"y type is {type(y)}")

x type is <class 'int'>
y type is <class 'float'>


## Python

You can use either single or double quotes for string literals.

In [5]:
print(type("Double quotes"))
print(type('Single quotes'))

<class 'str'>
<class 'str'>


## Lists

If you want to store multiple values in a single variable you can use lists. Under the hood lists are implemented as dynamic arrays.

In [6]:
#| output-location: slide
positions = ["First", "Second", "Third"] # List literals are denoted by square brackets

positions.append("Fourth") # Appending to a list, this appends in place
positions = [*positions, "Fifth"] # * - spread or unpacking operator

for position in positions: # Looping over lists
  print(position)
print("-------------------")

for idx, position in enumerate(positions): # If you also need the index of the list element
  print(f"{position}:{idx+1}")

First
Second
Third
Fourth
Fifth
-------------------
First:1
Second:2
Third:3
Fourth:4
Fifth:5


## Lists

Python makes it easy to slice lists:

In [7]:
primes = [2, 3, 5, 7, 11, 13, 17, 19]
print(primes[3]) # Get element of list
print(primes[1:3]) # Get a slice of a list
print(primes[:3]) # Empty gets interpreted as 0
print(primes[-3:-1]) # Negative numbers index from the end
print(primes[::2]) # You can also specify the step size for indexing

7
[3, 5]
[2, 3, 5]
[13, 17]
[2, 5, 11, 17]


## Lists

Python also has list comprehension:

In [8]:
numbers = [number for number in range(5)]
print([number**2 for number in numbers]) # ** - raising to a power
print([number for number in numbers if number % 2 == 0]) # You can also do ifs
print([number if number % 2 == 0 else -number for number in numbers]) # And if else, although the syntax is terrible

[0, 1, 4, 9, 16]
[0, 2, 4]
[0, -1, 2, -3, 4]


## Functions

Functions are defined as follows. Functions can have one, none or multiple return values. If a function does not explicitly return anything its return value is `None`.

In [9]:
#| output-location: slide
def void():
  print("Hello!")

print(void())

def next(x):
  return x+1

print(next(1))

def next_two(x):
  return x+1, x+2

print(next_two(1))

Hello!
None
2
(2, 3)


## Functions

All variables in Python are actually pointers to objects. All variables in functions are passed by value, but since all variables are pointers the behavior can be confusing at first glance. It's best to illustrate with example:

## Functions

In [10]:
#| output-location: slide
def next(x):
  # x inside the function scope is a new pointer that references the object that the input pointer references
  x += 1 # this line creates a new object in memory equal to x + 1 and makes x reference it
         # in consequence, the changes to x will not be visible outside the function scope
  return x

x = 1
print(next(x))
print(x)
print("--------------")

def append_1_inplace(x):
  x.append(1) # this line changes x in place so the change will be visible outside the function scope
  return x

x = [0]
print(append_1_inplace(x))
print(x)
print("--------------")

def append_1(x):
  x = [*x, 1] # this line creates a new object in memory and makes x reference it
              # in consequence, the changes to x will not be visible outside the function scope
  return x

x = [0]
print(append_1(x))
print(x)
print("--------------")

2
1
--------------
[0, 1]
[0, 1]
--------------
[0, 1]
[0]
--------------


## Dictionaries

Dictionaries store key value pairs

In [11]:
#| output-location: slide
positions = {"First": 1} # Dictionary literal
positions["Second"] = 2 # Adding new key value pair
positions = {**positions, "Third": 3} # You can use ** to spread dictionaries

for key in positions: # Looping over keys
  print(key)
print("-----------")

for key, value in positions.items():
  print(f"{key}:{value}")

positions["Fourth"] # Trying to access value that does not exist throws a KeyError

First
Second
Third
-----------
First:1
Second:2
Third:3


KeyError: 'Fourth'

## Numpy

`Numpy` is a Python package for scientific computing. The main feature of `numpy` are fixed size, fixed type multidimensional arrays. `Numpy` also implements a lot of operations on these arrays. Under the hood `numpy` is implemented in C, so performing operations on `numpy` arrays is very quick.

Here are some examples:

## Numpy

In [ ]:
#| output-location: slide
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2) # Sums componentwise
print(array1 * array2) # Multiplies componentwise
print("----------------")

matrix1 = np.array([
  [1, 2],
  [3, 4]
])
matrix2 = np.array([
  [5, 6],
  [7, 8]
])
print(matrix1 * matrix2) # Multiplies componentwise
print("----------------")
print(matrix1 @ matrix2) # Matrix multiplication, as defined in a linear algebra course
print("----------------")
print(np.linalg.eigvals(matrix1)) # Computes eigenvalues of matrix

[5 7 9]
[ 4 10 18]
----------------
[[ 5 12]
 [21 32]]
----------------
[[19 22]
 [43 50]]
----------------
[-0.37228132  5.37228132]


## Practice Task

We will use `numpy` quite heavily in the first few chapters.

The best way to learn a new programming language / package is to implement something in it.

You can try implementing Newton's algorithm for finding a solution to the nonlinear equation
$$
  F(x) = 0,
$$
where $F: \mathbb{R}^{n} \rightarrow \mathbb{R}^n$ is a differentiable function.

## Practice Task

Using Newton's method you approximate the solution by starting from initial guess $x_0$ and iterating by using the formula
$$
  DF(x_n)(x_{n+1}-x_n) = -F(x_n),
$$
where $DF$ is the [Jacobian](https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant) of $F$. Note that this is a system of linear equations.



## Practice Task

Tips:

1. You can approximately compute derivatives using the formula
$$
  f'(x) \approx \frac{f(x+h) - f(x)}{h}.
$$
where $h$ is a small number like $10^{-6}.$
2. When computing a new approximation you will need to solve a system of linear equations. You can do so using `numpy`. Have a look through its [documentation](https://numpy.org/doc/stable/reference/routines.html).

## Practice Task 

3. You can try
$$
  F(x, y) = (\cos(x)-\sin(y), \cos(x)).
$$